version: '3.8'
services:
  cmci-erp-client:
    image: cmci-erp-client
    container_name: cmci-erp-client
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./.env.prod
    volumes:
      - ./ngnix.conf:/etc/nginx/conf.d/default.conf